# =================================
# = Server
# =================================
server:
  port: 8080
  servlet:
    context-path: /v1

# =================================
# = Spring
# =================================
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dev_realmeet_db?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

# =================================
# = Logging
# =================================
logging:
  level:
    org.springframework: ERROR # INFO
    org.flywaydb: ERROR # INFO